export const STOCK_CARD_INSTRUCTION = `当且仅当回答涉及某个具体证券（股票、ETF、可转债）的策略、买点、卖点、止损、持仓管理、交易复盘或下一步动作时，在正常中文回答末尾追加一段机器数据。普通问答、市场泛聊，以及只核对账户事实且没有给出标的动作判断的回答不追加。
重要：复盘或盯盘回答中只要对具体证券给出了下一步、禁止买卖、触发条件、失效条件、重新开仓判断或持仓处理，就必须追加；不能因为问题同时涉及账户核对而省略。清仓、卖出压力解除、重新接回、震荡高抛低吸和上涨趋势继续持有都属于必须生成卡片的持仓状态。
格式必须严格为：<stock_strategy_cards>[JSON 数组]</stock_strategy_cards>，标签内不要使用 Markdown。
正常中文正文也必须按实体聚合：涉及账户时先按“## 成员名 → 账户名”分区，再在账户内按“### 6位代码 名称”组织；不涉及账户但有多个证券时，直接按“## 6位代码 名称”组织。每个标的的结论、当前价和数据时间、策略、触发条件、失效条件、风险、下一检查点必须放在同一个连续区块内。禁止先列全部标的、再另建多个同名“触发条件/失效条件/主要风险/下一检查点”区块。
每项字段：code（6位代码）、name、exchange、instrumentType（stock/etf/cbond）、accountScope（成员名 → 账户名）、source（holding/user/agent，分别表示持仓、我的收藏、AI发现）、currentPrice、changePercent、signal（immediate_buy/immediate_sell/strong_buy/strong_sell/prepare_buy/prepare_sell/watch）、stance（持仓管理/可关注/等待确认/暂不介入）、summary、strategy、decisionPolicyId、positionState、tradeIntent、triggerStrategy、triggerLevel（watch/confirm/actionable）、triggerKState（forming/closed）、actionPurpose、buyPoints、sellPoints、support、resistance、stopLoss、invalidation、risks、evidence、nextCheck、confidence（低/中/高）、dataAsOf、executionStatus（ready/review/blocked）、executionBlockers（执行阻断数组）、executionValidUntil（立即信号失效时间，ISO时间）。
signal 必须准确区分七档：immediate_buy/immediate_sell 是最高等级，表示当前点位已经满足条件，出现异动·上涨/下跌；strong_buy/strong_sell 的用户可见名称是“关注·上涨/关注·下跌”，表示闭合K线与独立证据已经形成，需要优先人工复核；prepare_buy/prepare_sell 表示闭合证据已进入上涨/下跌观察阶段，但仍需等待明确的下一确认点；watch 表示仅关注观察，尚未进入动作准备。position_guidance.state=full_exit_ready 默认写 strong_sell；只有当前价仍满足卖点、可用数量与活动委托已核对、行情未过期且所有执行闸门通过时才能升级 immediate_sell。reentry_ready/range_low_add/trend_add_ready 必须根据证据写 strong_buy 或 prepare_buy；只有当前价已经满足买点、账户现金/总资产/冻结/活动委托/交易费用/风险预算均已核对、可买数量明确、纪律正常且没有事件风险缺口时才能升级 immediate_buy。range_high_reduce 写 strong_sell 或 prepare_sell；trend_hold 默认写 watch，且 strategy 必须明确核心仓继续持有。形成中的K线、单纯触价、证据不足只能写 watch。
immediate_buy/immediate_sell 必须同时满足：confidence=高、executionStatus=ready、executionBlockers=[]、accountScope/currentPrice/dataAsOf 完整，并分别提供带当前价格的 buyPoints/sellPoints；executionValidUntil 必须晚于 dataAsOf 且最多只允许 5 分钟有效，超过该时间必须重新分析当前报价。文案不得再出现“等待下一根K线、等待站稳、数量待确认、现金待确认、费用待确认、委托待确认、暂不执行”等阻断语义。任何一项不满足都必须降为 strong_buy/strong_sell，并把原因写入 executionBlockers。prepare_buy 必须有 buyPoints，prepare_sell 必须有 sellPoints；strong_buy/strong_sell 也必须分别有对应买点/卖点。卡片等级只提供决策辅助，immediate 也不会连接券商或自动下单。
buyPoints 和 sellPoints 是数组，每项为 {"label":"名称","price":"价格或区间","condition":"必须满足的条件"}。没有可靠证据的价格、涨跌幅和关键位填 null，不得猜测；没有买卖点就给空数组。卡片只是条件化分析，不得把建议写成已成交或自动下单。`

export const AUTOMATION_STOCK_CARD_INSTRUCTION = `${STOCK_CARD_INSTRUCTION}
盘中盯盘必须为本次实际分析到的每个证券生成策略卡，不能只给纯文本；最多 8 张，并确保 code 与本次工具证据一致。同一证券存在于多个持仓账户时，必须按 accountScope 一账户一卡，策略、成本、数量和动作不能合并。持仓卡 source=holding；我的收藏和AI发现卡分别写 source=user/agent，并把 accountScope 写成实际用于寻找买点的主账户，即使该账户当前空仓也不能省略。候选池刷新任务的市场候选 source=agent 且可以不写 accountScope，但候选池没有账户执行事实，因此禁止输出 immediate_buy/immediate_sell。异动级、关注级和观察级信号卡片必须按等级排在 JSON 数组最前面：持仓通道出现 closed/actionable 的上涨、重新接回、震荡低吸、下跌、震荡高抛或清仓证据时，signal 分别写 strong_buy 或 strong_sell（用户可见为"关注·上涨"或"关注·下跌"）；只有当前点位与全部执行闸门同时通过时才进一步升级 immediate_buy/immediate_sell。自选通道出现在 new_buy_signals 中默认写 strong_buy，不能仅因进入 new_buy_signals 就写 immediate_buy。持仓的闭合证据已进入接回/低吸或减仓/下跌观察但尚未达到关注级信号时写 prepare_buy/prepare_sell。上涨趋势未破坏且没有明确退出证据时只能写 watch，不得因为普通动能转弱写 prepare_sell。普通观察、重复 buy_ready、形成中K线和证据不足一律写 watch。每张卡都要写清触发条件、失效条件、执行状态和数据时间。
所有定时任务只要输出具体买卖点或 immediate/strong/prepare 买卖信号，就必须使用本轮 Trade Master 证据中 decision_policy_id=rolling-position-v25-robust-70 的统一模型结果；没有本轮 plan 或 watchlist 统一模型证据的候选池、回测、策略进化、健康检查等任务，只能做研究展示，不得生成当前买卖点或动作信号。decisionPolicyId 必须原样填写 rolling-position-v25-robust-70；positionState、tradeIntent 必须原样取自 position_guidance；triggerStrategy、triggerLevel、triggerKState 必须原样取自对应 trigger_signal 或 latest_signals，禁止自行改写。strong/immediate 只允许使用 closed/actionable 信号；prepare 只允许使用 closed 且 confirm/actionable 的信号。任何字段缺失、方向冲突或仍是 forming 时都必须写 watch，并把 buyPoints/sellPoints 置为空数组。
所有 buyPoints、sellPoints、support、resistance、stopLoss 和 invalidation 必须直接来自本轮统一模型证据中的 trigger_signal、latest_signals、position_guidance 或 downside_risk；价格优先使用 trigger_signal.price，条件和失效说明优先使用 trigger_signal.reasons 与 trigger_signal.invalidation。统一模型没有给出对应闭合信号时，相关买卖点数组必须为空，禁止由语言模型自行补点、猜区间或把候选模型状态改写成买卖信号。
actionPurpose 必须说明这次动作要完成什么，并严格按统一模型状态填写：full_exit_ready=清仓避险；range_break_reduce/defense_reduce=风险减仓；trend_top_reduce=逃顶 · 卖出准备做T；range_high_reduce=区间高抛 · 卖出准备做T；range_low_add=区间低吸；trend_add_ready=趋势回踩买入；reentry_watch/entry_watch=准备接回；trend_hold=持有核心仓；reentry_ready/entry_ready 且 tradeIntent=t_reentry 时=买入完成做T，tradeIntent=high_low_reentry 时=高抛低吸完成，risk_reclaim/risk_reentry 时=风险释放后接回，其余 entry_ready=新开仓。观察卡写仅观察。不得只写“买入”或“卖出”代替动作目的。`
